name: minify

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    env:
      pbranch: production
      prepo: ${{github.repository}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Minify Actions
      uses: amireshoon/minifyAction@main
      with:
        push-branch: $pbranch
        repo: $prepo
    - name: Running Tests
      run: |
        minifier.sh $pbranch $prepo
    - name: Commiting changes
      run: |
        cd github/workspace
        git config --global user.name 'Minify-Action-Bot'
        git config --global user.email '<>'
        git status
        git add -A
        git commit -m "Minified files"
        git push -u origin $pbranch
    name: Minify
